### ISSUE TITLE
Questions about test automation and migrations

### ISSUE THREAD

**Issue by datarttu** [datarttu/sujuikoDB#19]
Look at the project in its current state. At the moment, we do not have any automated tests but one has to eyeball for errors on the console when running DDL scripts and queries (and hopefully remember to use transactions to be able to revert to the initial state...).

On the other hand, developing test automation takes time. It is also not as straightforward with databases and complex data: extracting or creating mock data and writing tests with them for various corner cases in HFP errors, for instance, is demanding. So far, I have just modified / amended the database model accordingly whenever I have encountered a weird case in manual experimenting.

- What kind of automated tests should we write, if any? What are some critical places for them, considering time spent vs. benefit?
- Suggestions for setting up a minimum effort test framework for regression tests - if we want to (partially) automate the process of ensuring that given a set of test data, our functions return the correct set of result data. E.g. RegreSQL & Docker?

Making changes to an existing database structure, i.e. migrations, is also a question. For the time being, I don't have a version running on server and the amount of data is so small that the dev version of the db can be easily started and hydrated from scratch. However, using migrations can be relevant sooner or later.

- What are some good example SQL(-only) repositories using e.g. [Migra](https://github.com/djrobstep/migra) where one could easily see the process of developing the original SQL scripts and building up related migration scripts?
- For final HFP observation tables, we are and will be using [TimescaleDB](https://docs.timescale.com/latest/introduction) that works as an abstraction layer for partitioning a table into subtables based on a timestamp key column. Can such extensions be a problem with database model migrations?

**Comment by haphut** [comment]
Warning! Don't let this post distract you from what you find important right now. :)

We'll get back to migrations as a separate topic. I'll focus on testing strategy now.

And you probably are following or consciously breaking some of this advice already.

# Why write tests?

Testing has at least three purposes:
1. Designing APIs
1. Documentation
1. Quality assurance

## Designing APIs

Test-driven development (TDD) raves about this. If one has to write failing tests before writing the implementation that makes the tests pass, the APIs become in some sense simpler.

## Documentation

One of the easiest ways to understand a new project is to read its tests, assuming there are comprehensive tests.

The tests are hopefully clearly named and contextualized.

The tests might answer what the software is supposed to achieve, in detail.

As functions, helpers and libraries commonly hide complexity, the tests show the presumably easier, user-facing side of the code.

And passing tests are in a way guaranteed to be up-to-date, unlike prose.

## Quality assurance

We wish for the code to act correctly.

# What to test?

Where have you found most mistakes?

What kind of mistakes have they been? That might affect the type of testing required.

Where do you have to be most careful when you are writing code?

What parts of the code do you not trust?

Aim to find easy wins in those places.

# Testing processes

For such a data analysis project, I would separate testing the code from validating the data.

Run the code tests during development and in the CI.

Run the data validation for the test data set during development and in the CI.

Also run the data validation for every import in production as well. That's one difference between code tests and data validation.

## Testing code

For this project unit tests and property-based tests seem useful.

A property-based test generates random input for a function according to given invariants and tests the output of the function for other invariants. The aim is to find bugs by creating and running thousands of "unit tests" on the fly.

I find [Beyond Unit Tests](https://www.hillelwayne.com/talks/beyond-unit-tests/) by Hillel Wayne a practical intro to property-based testing. Wayne describes a tool called Hypothesis for Python. [Hedgehog for R](https://github.com/hedgehogqa/r-hedgehog) seems similar. Disclaimer: I have not used it.

## Validating data

Property-based testing has similarities to how I think about data validation. In data validation, we test for invariants that should hold for all or a subset of the data. Instead of random input, we use a lot of curated input.

Make a data set that covers the cases the code should be able to handle. You might need several test data sets. The test data sets might need to include should-pass and should-fail data.

I like [this guide](https://github.com/jtleek/datasharing) about how to treat data. Some of it is applicable here, e.g. understanding the difference between raw data and processed data.

If possible, the test data set should start from raw data. If you split sujuiko into smaller pieces, e.g. separate the HFP data cleaning into [hslhfp](https://github.com/datarttu/hslhfp), then this repository should treat the output of hslhfp as the raw data.

Obviously we hope to write automated tests so that manual inspection of the processing results is not needed.

### Stages

Often data cleaning processes from raw data to a coherent data set or a coherent database occur in several stages. One likely needs data validation for every stage.

In the picture below, arrows with "parse" or "process" need code tests. Arrows with "validate" are about data validation.

```
                                                                                ,.-^^-._
                                                                               |-.____.-|
                                                                               |        |
                                                                               |        |
                                                                               |        |
     ┌────────┐          ┌───────┐          ┌───┐          ┌───────┐           '-.____.-'
     │Raw data│          │Stage 1│          │...│          │Stage n│           Coherent
     └────────┘          └───────┘          └───┘          └───────┘           database
         │       parse       │                │                │                  │
         │  ─ ─ ─ ─ ─ ─ ─ ─ >│                │                │                  │
         │                   │                │                │                  │
         │                   ─ ─ ┐            │                │                  │
         │                       | validate   │                │                  │
         │                   < ─ ┘            │                │                  │
         │                   │                │                │                  │
         │                   │    process     │                │                  │
         │                   │ ─ ─ ─ ─ ─ ─ ─ >│                │                  │
         │                   │                │                │                  │
         │                   │                ─ ─ ┐            │                  │
         │                   │                    | validate   │                  │
         │                   │                < ─ ┘            │                  │
         │                   │                │                │                  │
         │                   │                │    process     │                  │
         │                   │                │ ─ ─ ─ ─ ─ ─ ─ >│                  │
         │                   │                │                │                  │
         │                   │                │                ─ ─ ┐              │
         │                   │                │                    | validate     │
         │                   │                │                < ─ ┘              │
         │                   │                │                │                  │
         │                   │                │                │      write       │
         │                   │                │                │ ─ ─ ─ ─ ─ ─ ─ ─ >│
         │                   │                │                │                  │
         │                   │                │                │                  │─ ─ ┐
         │                   │                │                │                  │    | check or
         │                   │                │                │                  │< ─ ┘ validate
         │                   │                │                │                  │
         │                   │                │                │                  │
         │                   │                │                │                  │
```

Aim to write tests into as early stage as possible without rewriting the next processing stage code in the test code. That way it will be easier to find out why the data records failed.

In the coherent database we hopefully have constraints and possibly triggers to check the data validity. Hopefully these final validations can be kept light if the earlier validations have been comprehensive.

### Failing data records

During the validation, you can:
1. fail the whole data set if any record fails the validation,
1. log and set aside the failing records or
1. mark the failing records as such and pass them to the next stage anyway.

My intuition for this problem space says to set aside the failing records and not to pass them forward. If setting them aside is hard, we might be using the wrong tools or wrong data types or constraints for that particular processing stage.

### Data validation creation process

Come up with invariants that should hold and write them in code. This takes most of the time.

Despite our efforts, eventually two kinds of data handling bugs come up:
1. Some data records pass into the coherent database but should not.
1. Some data records fail the data validation but should not.

When that happens:
1. Investigate why it happens.
1. Add one, some or all of the interesting records into the test data set.
1. Write failing tests.
1. Fix the processing or the data validation code until they all pass.
